RogueFinancialPortal/Models/HouseHold.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RogueFinancialPortal.Models
{
    public class HouseHold
    {
        public int Id { get; set; }
        #region Parents/Children
        public string OwnerId { get; set; }   
        public virtual ApplicationUser Owner { get; set; }

        #endregion
        #region Actual Properties
        [Display(Name = "Name")]
        public string HouseHoldName { get; set; }
        public string Greeting { get; set; }

        public DateTime Created { get; set; }
        [Display(Name = "Delete HouseHold Item")]
        public bool IsDeleted { get; set; }
        #endregion
        #region virtual   
        public virtual ICollection<ApplicationUser> Members { get; set; }
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }


        #endregion
        #region Constructor
        public HouseHold()
        {
            Budgets = new HashSet<Budget>();
            BankAccounts = new HashSet<BankAccount>();
            Members = new HashSet<ApplicationUser>();
            Invitations = new HashSet<Invitation>();
            Notifications = new HashSet<Notification>();

            Created = DateTime.Now;
            OwnerId = HttpContext.Current.User.Identity.GetUserId();
        }
        public HouseHold(string houseHoldName, string greeting)
        {
            Budgets = new HashSet<Budget>();
            BankAccounts = new HashSet<BankAccount>();
            Members = new HashSet<ApplicationUser>();
            Invitations = new HashSet<Invitation>();
            Notifications = new HashSet<Notification>();
            HouseHoldName = houseHoldName;
            Greeting = greeting;
            Created = DateTime.Now;
            OwnerId = HttpContext.Current.User.Identity.GetUserId();
        }
        public HouseHold(bool inSeed)
        {
            Budgets = new HashSet<Budget>();
            BankAccounts = new HashSet<BankAccount>();
            Members = new HashSet<ApplicationUser>();
            Invitations = new HashSet<Invitation>();
            Notifications = new HashSet<Notification>();

            Created = DateTime.Now;
        }
        #endregion
    }
}

RogueFinancialPortal/Controllers/HouseHoldsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using RogueFinancialPortal.Extensions;
using RogueFinancialPortal.Helpers;
using RogueFinancialPortal.Models;
using RogueFinancialPortal.ViewModels;

namespace RogueFinancialPortal.Controllers
{
    [Authorize]
    public class HouseHoldsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserRoleHelper roleHelper = new UserRoleHelper();
        // GET: HouseHolds
        public ActionResult Index()
        {
            var houseHolds = db.HouseHolds.Include(h => h.Owner);
            return View(houseHolds.ToList());
        }

        // GET: HouseHolds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            return View(houseHold);
        }



        [Authorize(Roles = "Head")]
        [HttpGet]
        public ActionResult HouseHoldWizard()
        {
            //var model = new HouseHoldCreationWizardVM();
            //model.HouseHoldId = (int)User.Identity.GetHouseHoldId();
            //if(model.HouseHoldId == null)
            //{
            //    return RedirectToAction("Create");
            //}
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult>  HouseHoldWizard(List<BankAccountWizardVM> BankAccounts, string Greeting, string HouseHoldName)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            //if (user.HouseHoldId == null)
            //{
                HouseHold newHouseHold = new HouseHold(HouseHoldName, Greeting);
                db.HouseHolds.Add(newHouseHold);
                db.SaveChanges();

                user.HouseHoldId = newHouseHold.Id;
                roleHelper.UpdateUserRole(user.Id, "Head");
                db.SaveChanges();
                await AuthorizeExtensions.RefreshAuthentication(HttpContext, user);

                if (BankAccounts != null)
                {
                    foreach (var bankAccount in BankAccounts)
                    {
                        BankAccount newBankAccount = new BankAccount(bankAccount.StartingBalance, bankAccount.WarningBalance, bankAccount.BankAccountName);
                        db.BankAccounts.Add(newBankAccount);
                        db.SaveChanges();
                        if (bankAccount.Budgets != null)
                        {
                            foreach (var budget in bankAccount.Budgets)
                            {
                                Budget newBudget = new Budget();
                                newBudget.BudgetName = budget.BudgetName;
                                newBudget.Description = budget.Description;
                                newBudget.BankAccountId = newBankAccount.Id;

                                db.Budgets.Add(newBudget);
                                db.SaveChanges();

                                if (budget.BudgetItems != null)
                                {
                                    foreach (var budgetItem in budget.BudgetItems)
                                    {
                                        BudgetItem newBudgetItem = new BudgetItem();
                                        newBudgetItem.ItemName = budgetItem.ItemName;
                                        newBudgetItem.Description = budgetItem.Description;
                                        newBudgetItem.TargetAmount = budgetItem.TargetAmount;
                                        newBudgetItem.BudgetId = newBudget.Id;


                                        db.BudgetItems.Add(newBudgetItem);
                                        db.SaveChanges();
                                    }
                                }
                            }
                        }

                    //}
                }
            }

            return RedirectToAction("Index", "Home");

        }
        // POST: HouseHolds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598. 
        // GET: HouseHolds/Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Default")]

        public async System.Threading.Tasks.Task<ActionResult> Create([Bind(Include = "Id,HouseHoldName,Greeting")] HouseHold houseHold)
        {
            if (ModelState.IsValid)
            {
                houseHold.Created = DateTime.Now;
                db.HouseHolds.Add(houseHold);
                db.SaveChanges();
                var user = db.Users.Find(User.Identity.GetUserId());
                user.HouseHoldId = houseHold.Id;
                roleHelper.UpdateUserRole(user.Id, "Head");
                db.SaveChanges();
                await AuthorizeExtensions.RefreshAuthentication(HttpContext, user);
                return RedirectToAction("HouseHoldWizard");
            }

            return View(houseHold);
        }


        // GET: HouseHolds/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "FirstName", houseHold.OwnerId);
            return View(houseHold);
        }

        // POST: HouseHolds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OwnerId,HouseHoldName,Greeting,Created,IsDeleted")] HouseHold houseHold)
        {
            if (ModelState.IsValid)
            {
                db.Entry(houseHold).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "FirstName", houseHold.OwnerId);
            return View(houseHold);
        }

        public ActionResult LeaveAsync()
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            var role = roleHelper.ListUserRoles(userId).FirstOrDefault();
            switch (role)
            {
                case "Head":
                    var memberCount = db.Users.Where(u => u.HouseHoldId == user.HouseHoldId).Count() - 1;
                    if (memberCount >= 1)
                    {
                        TempData["Message"] = $"You are unable to leave the Household! There are still <b>{memberCount}<b> other members in the household, you must select one to replace you as head of Household";
                        ViewBag.Members = new SelectList(db.Users.Where(u => u.HouseHoldId == user.HouseHoldId).ToList(), "Id", "FullName");
                        ViewBag.Ishead = true;
                    }
                    else
                    {
                        TempData["Message"] = $"You are Leaving the HouseHold. The HouseHold and all data will be Delete! Are you sure you want to leave?";
                        ViewBag.Ishead = false;
                    }
                    return View();
                case "Member":
                    TempData["Message"] = $"You are Leaving the HouseHold. Are you sure you want to leave?";
                    ViewBag.Ishead = false;
                    return View();

                default:
                    return RedirectToAction("index", "Home");

            }
        }

        // GET: HouseHolds/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            return View(houseHold);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LeaveAsync(string newHeadUserId)
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            var household = db.HouseHolds.Find(user.HouseHoldId);
            var role = roleHelper.ListUserRoles(userId).FirstOrDefault();
            switch (role)
            {
                case "Head":
                    if (newHeadUserId != null)
                    {
                        household.OwnerId = newHeadUserId;
                        roleHelper.UpdateUserRole(newHeadUserId, "Head");
                        var NewUserHead = db.Users.Find(newHeadUserId);
                        await AuthorizeExtensions.RefreshAuthentication(HttpContext, NewUserHead);
                    }
                    else
                    {
                        household.IsDeleted = true;
                        user.HouseHoldId = null;
                    }

RogueFinancialPortal/Views/HouseHolds/Create.cshtml
@model RogueFinancialPortal.Models.HouseHold

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HouseHold</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OwnerId, "OwnerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseHoldName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HouseHoldName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HouseHoldName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Greeting, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Greeting, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Greeting, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RogueFinancialPortal/Views/HouseHolds/Delete.cshtml
@model RogueFinancialPortal.Models.HouseHold

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HouseHold</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Owner.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HouseHoldName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HouseHoldName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Greeting)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Greeting)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RogueFinancialPortal/Views/HouseHolds/Details.cshtml
@model RogueFinancialPortal.Models.HouseHold

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>HouseHold</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Owner.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HouseHoldName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HouseHoldName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Greeting)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Greeting)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RogueFinancialPortal/Views/HouseHolds/Edit.cshtml
@model RogueFinancialPortal.Models.HouseHold

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HouseHold</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerId, "OwnerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseHoldName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HouseHoldName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HouseHoldName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Greeting, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Greeting, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Greeting, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RogueFinancialPortal/Views/HouseHolds/Index.cshtml
@model IEnumerable<RogueFinancialPortal.Models.HouseHold>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Owner.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HouseHoldName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Greeting)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Owner.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HouseHoldName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Greeting)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDeleted)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

RogueFinancialPortal/Views/HouseHolds/LeaveAsync.cshtml
@using (Html.BeginForm("LeaveAsync", "HouseHolds", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row  justify-content-center">
    <div class="col-lg-4 m-t-40 col-md-6  ">
        <div class="card h-100">
            <div class="card-body ">
                <h4 class=" ">Leave HouseHold</h4>
                <div class="card-body">
                    <div class=" row">
                        <p id="message" class="control-label ">@Html.Raw(TempData["Message"])</p>

                    </div>
                    @if (ViewBag.IsHead)
                    {
                        <div class="form-group row">
                            <label class="control-label ">Please select a replacement Head of the HouseHold!</label>
                            <div class="col-md-">
                                @Html.DropDownList("Members", null, new { @class = "form-control" })
                            </div>
                        </div>

                    }

                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="offset-sm-3 col-md-9">
                                <button type="submit" id="btn-submit" class="btn btn-success"> <i class="fa fa-check"></i> Submit</button>

                                @Html.ActionLink("Cancel", "Index", "Manage", new { @type = "button", @class = "btn btn-danger" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
}